#!/bin/sh

set -e

# Note: eth1
IP=`ip -f inet addr | grep 'inet.*eth1' | awk '{print $2}' | cut -d/ -f1`

cat > /etc/hosts <<EOF
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
$IP $HOSTNAME
EOF

if [ -z "$@" ]; then
    exec  mesos-master --hostname=$IP --ip=$IP --registry=in_memory
else
    exec "$@"
fi
