---
# build
- file: path=/usr/src/consul state=absent
- copy: src=./ dest=/usr/src/consul

- shell: docker build -t consul . chdir=/usr/src/consul

# remove if commandline arguments have changed
- template: src=consul.j2 dest=/usr/local/sbin/docker-consul mode=0755
  register: result

# remove if container is not up-to-date
- shell: test "`docker inspect consul | python -c \"import json, sys; print json.load(sys.stdin)[0]['Image']\"`" = "`docker inspect consul:latest | python -c \"import json, sys; print json.load(sys.stdin)[0]['Id']\"`"
  ignore_errors: true
  register: uptodate
  
- shell: docker rm -f consul
  ignore_errors: true
  when: result|changed or uptodate|failed

# start if container is stopped, create if container does not exist
- shell: docker ps -a | awk '{print $NF}' | grep -q '^consul$' && docker inspect consul
  ignore_errors: true
  register: result
  
- shell: docker start consul
  when: "result|success and result.stdout.find('\"Running\": false,') != -1"

- shell: /usr/local/sbin/docker-consul
  when: result|failed
